# Generated by Django 5.2.5 on 2025-08-19 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100, unique=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='homepage', max_length=100, unique=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('today_visits', models.IntegerField(default=0)),
                ('last_visit_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visit_counter',
            },
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('page_visited', models.CharField(max_length=100)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visit_logs',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_san_pham', models.CharField(max_length=50, unique=True)),
                ('ten_san_pham', models.CharField(max_length=255)),
                ('mo_ta', models.TextField()),
                ('so_trang', models.IntegerField(blank=True, null=True)),
                ('kich_thuoc', models.CharField(blank=True, max_length=100)),
                ('loai_bia', models.CharField(blank=True, max_length=50)),
                ('duong_dan_ngoai', models.URLField(blank=True, null=True)),
                ('gia_mac_dinh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='anh_san_pham/')),
                ('yeu_thich', models.IntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('loai_san_pham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_phams', to='core.loaisanpham')),
            ],
        ),
    ]
