# Generated by Django 5.2.4 on 2025-09-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_linkclickhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="loaisanpham",
            name="layout",
            field=models.IntegerField(default=0),
        ),
    ]
