# Generated by Django 5.2.6 on 2025-10-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sanphamloai_alter_sanpham_loai_san_pham'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaisanpham',
            name='sort_oder',
            field=models.IntegerField(default=0),
        ),
    ]
