# Generated by Django 5.2.4 on 2025-09-17 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_sanpham_loai_san_pham_sanpham_loai_san_pham"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sanpham",
            name="loai_san_pham",
        ),
        migrations.AddField(
            model_name="sanpham",
            name="loai_san_pham",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="san_phams",
                to="core.loaisanpham",
            ),
        ),
    ]
