# Generated by Django 5.2.4 on 2025-09-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_sanpham_loai_san_pham_sanpham_loai_san_pham"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="styleconfig",
            name="font_size",
        ),
        migrations.AddField(
            model_name="styleconfig",
            name="background",
            field=models.CharField(
                blank=True, help_text="Màu nền chung (hex)", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="styleconfig",
            name="font_weight",
            field=models.CharField(
                blank=True,
                help_text="Font weight (px, em, rem)",
                max_length=20,
                null=True,
            ),
        ),
    ]
